# fastlane/Fastfile

platform :android do
  desc "Upload a new Android version to the Google Play Store"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      release_status: 'completed',
      aab: ENV['ANDROID_BUILD_FILE_PATH'],
      mapping: ENV['ANDROID_SYMBOL_FILE_PATH']
    )
  end
end

platform :ios do
  before_all do |lane, options|
    app_store_connect_api_key(
      key_id: ENV['APPSTORE_KEY_ID'],
      issuer_id: ENV['APPSTORE_ISSUER_ID'],
      key_content: ENV["APPSTORE_P8"]
    )
  end

  desc "Build a new ad-hoc build"
  lane :adhoc do
    build(type: 'adhoc')

    if ENV['GITHUB_OUTPUT'].to_s.length > 0
      sh("echo \"ipa-output-path=#{Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]}\" >> \"$GITHUB_OUTPUT\"")
      sh("echo \"dsym-output-path=#{Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH]}\" >> \"$GITHUB_OUTPUT\"")
    end
  end

  desc "Deliver a new beta build to Apple TestFlight"
  lane :beta do
    # Missing Export Compliance can also be set through Deliverfile
    update_info_plist(
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcodeproj",
      plist_path: 'Info.plist',
      block: proc do |plist|
        plist['ITSAppUsesNonExemptEncryption'] = false
      end
    )

    build(type: 'appstore')

    upload_to_testflight(skip_waiting_for_build_processing: true)

    upload_symbols_to_crashlytics(
      binary_path: "#{ENV['IOS_BUILD_PATH']}/Pods/FirebaseCrashlytics/upload-symbols",
      app_id: ENV['FIREBASE_IOS_APP_ID']
    )
  end

  desc "Create .ipa"
  private_lane :build do |options|
    setup_ci

    match(
      type: options[:type],
      storage_mode: 'git',
      git_url: ENV['MATCH_URL'],
      git_branch: ENV['MATCH_GIT_BRANCH'],
      git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'],
      app_identifier: ENV['IOS_BUNDLE_ID']
    )

    # Unity has specific requirements around codesigning that we have to handle
    # See https://github.com/fastlane/fastlane/discussions/17458 for context
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcodeproj"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_#{options[:type]}_team-id"],
      code_sign_identity: 'iPhone Distribution',
      targets: 'Unity-iPhone',
      path: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcodeproj",
      profile_name: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_#{options[:type]}_profile-name"],
      profile_uuid: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_#{options[:type]}"]
    )

    build_app(
      workspace: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcworkspace",
      scheme: 'Unity-iPhone',
      xcargs: '-allowProvisioningUpdates'
    )
  end
end
