// <auto-generated>
// 이 파일은 UILayerAddressConstantsGenerator에 의해 자동 생성됩니다.
// 수동으로 수정하지 마세요.
// </auto-generated>

namespace CookApps.UIManagements
{
    internal static class UILayerConstants
    {
        public static string GetUILayerAddress(string uiLayerName)
        {
            return uiLayerName switch
            {
                "InGameMain" => "Prefabs/UI/InGame/InGameMain.prefab",
                "LoadingMain" => "Prefabs/UI/Loading/LoadingMain.prefab",
                "TopPanelBar" => "Prefabs/UI/TopPanelBar/TopPanelBar.prefab",
                "LobbyMain" => "Prefabs/UI/Lobby/LobbyMain.prefab",
                "TitleMain" => "Prefabs/UI/Title/TitleMain.prefab",
                "PopupInGamePause" => "Prefabs/Popup/InGamePause/PopupInGamePause.prefab",
                "PopupCommon" => "Prefabs/Popup/Common/PopupCommon.prefab",
                "PopupItemRewardEffect" => "Prefabs/Popup/Common/PopupItemRewardEffect.prefab",
                _ => string.Empty
            };
        }

        public static string GetSceneAddress(string sceneName)
        {
            return sceneName switch
            {
                "Title" => "Scenes/Title.unity",
                "Lobby" => "Scenes/Lobby.unity",
                "InGame" => "Scenes/InGame.unity",
                "Loading" => "Scenes/Loading.unity",
                _ => string.Empty
            };
        }
    }
}
