name: 🚀 Release to Apple App Store

on:
  workflow_dispatch:
    inputs:
      clean-dir:
        description: "Clean directories before build"
        required: false
        default: false
        type: boolean

concurrency:
  group: apple-prod
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  build:
    name: Build for iOS and release to Apple App Store
    runs-on: [self-hosted, macOS, ARM64, unity-builder, production]
    steps:
      # Checkout
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: ${{ github.event.inputs.clean-dir == 'true' }}

      # Unity build
      - name: Request Unity license
        id: license
        uses: cookapps-devops/tech-build/.github/actions/request-license@v1
      - name: Build
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_SERIAL: ${{ steps.license.outputs.unity-serial }}
          UNITY_EMAIL: ${{ steps.license.outputs.unity-email }}
          UNITY_PASSWORD: ${{ steps.license.outputs.unity-password }}
        with:
          targetPlatform: iOS
          versioning: None
          buildMethod: CookApps.Build.CookAppsBuild.BuildBatchMode
          customParameters: >
            -buildName ios-apple-prod
            -EnableCacheServer
            -cacheServerEndpoint ${{ vars.UNITY_ACCELERATOR_ENDPOINT }}
            -cacheServerNamespacePrefix ${{ github.repository }}
            -cacheServerEnableDownload true
            -cacheServerEnableUpload true
      - name: Return Unity license
        if: ${{ always() && steps.license.outcome == 'success' }}
        uses: cookapps-devops/tech-build/.github/actions/return-license@v1
        with:
          unity-license: ${{ toJSON(steps.license.outputs) }}
      - name: Extract data from build summary file
        id: build-summary
        uses: cookapps-devops/tech-build/.github/actions/build-summary@v1
        with:
          build-summary-file-path: Builds/build-summary.json

      # Xcode build
      - name: Create GitHub app token to access code-signing repository
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.MATCH_GITHUB_APP_ID }}
          private-key: ${{ secrets.MATCH_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ios-certificates
      - name: Create basic authorization for fastlane match
        id: app-auth
        env:
          GITHUB_USERNAME: ${{ vars.MATCH_GITHUB_APP_USERNAME }}
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: echo "authorization=$(echo -n ${GITHUB_USERNAME}:${TOKEN} | base64)" >> $GITHUB_OUTPUT
      - name: Fix file permissions and run fastlane
        id: xcode
        env:
          APPLE_CONNECT_EMAIL: ${{ secrets.APPLE_CONNECT_EMAIL }}
          APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          MATCH_URL: ${{ secrets.MATCH_URL }}
          MATCH_GIT_BRANCH: ${{ vars.MATCH_GIT_BRANCH }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ steps.app-auth.outputs.authorization }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
          IOS_BUILD_PATH: ${{ steps.build-summary.outputs.output-path }}
          IOS_BUNDLE_ID: ${{ steps.build-summary.outputs.identifier }}
          FIREBASE_IOS_APP_ID: ${{ vars.FIREBASE_IOS_APP_ID }}
        run: |
          find $IOS_BUILD_PATH -type f -name "**.sh" -exec chmod +x {} \;
          fastlane ios beta

      # Notify Slack
      - name: Notify Slack
        if: success() || failure()
        uses: slackapi/slack-github-action@v1
        env:
          # Post a message by utilizing incoming webhook
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

          # Environment variables for payload
          TEXT: ${{ job.status == 'success' && 'Build finished successfully!' || job.status == 'failure' && 'Failed to build the application.' }}
          JOB_STATUS_COLOR: ${{ job.status == 'success' && '#00FF00' || job.status == 'failure' && '#FF0000' }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          PLATFORM: ${{ steps.build-summary.outputs.platform }}
          VERSION: ${{ steps.build-summary.outputs.version }}
          VERSION_CODE: ${{ steps.build-summary.outputs.version-code }}
          DOWNLOAD_URL: ${{ job.status == 'success' && format('https://testflight.apple.com/v1/app/{0}', vars.IOS_APP_ID) || job.status == 'failure' && 'https://github.com' }}
        with:
          payload-file-path: .github/slack/payload-slack-content.json
